name: Caching 

on:
  push

jobs:
  simple-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Restore cache    #checks if the cached file is present and tried to restore it
        uses: actions/cache@v3
        with:
          path: ./my-temp-folder
          key: test-cache-v1

      - name: Create file if cache miss  #runs only if the cache miss happens
        run: |
          if [ -f ./my-temp-folder/hello.txt ]; then
            echo " Cache Hit: File exists!"
            cat ./my-temp-folder/hello.txt
          else
            echo " Cache Miss: Creating file..."
            mkdir -p ./my-temp-folder
            echo "This file is now cached!" > ./my-temp-folder/hello.txt
          fi

      - name: Save cache # to save the cached file after the cache miss
        uses: actions/cache@v3
        with:
          path: ./my-temp-folder
          key: test-cache-v1
